---
- name: afp
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: afp enable
    ansible.posix.firewalld:
      zone: public 
      service: afp 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  