---
- name: amqp
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: amqp enable
    ansible.posix.firewalld:
      zone: public 
      service: amqp 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  