---
- name: apcupsd
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: apcupsd enable
    ansible.posix.firewalld:
      zone: public 
      service: apcupsd 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  