---
- name: bb
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: bb enable
    ansible.posix.firewalld:
      zone: public 
      service: bb 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  