---
- name: bitcoin-testnet-rpc
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: bitcoin-testnet-rpc enable
    ansible.posix.firewalld:
      zone: public 
      service: bitcoin-testnet-rpc 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  