---
- name: bitcoin-testnet
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: bitcoin-testnet enable
    ansible.posix.firewalld:
      zone: public 
      service: bitcoin-testnet 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  