---
- name: bitcoin
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: bitcoin enable
    ansible.posix.firewalld:
      zone: public 
      service: bitcoin 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  