---
- name: bittorrent-lsd
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: bittorrent-lsd enable
    ansible.posix.firewalld:
      zone: public 
      service: bittorrent-lsd 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  