---
- name: ceph-mon
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ceph-mon enable
    ansible.posix.firewalld:
      zone: public 
      service: ceph-mon 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  