---
- name: cfengine
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: cfengine enable
    ansible.posix.firewalld:
      zone: public 
      service: cfengine 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  