---
- name: checkmk-agent
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: checkmk-agent enable
    ansible.posix.firewalld:
      zone: public 
      service: checkmk-agent 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  