---
- name: cockpit
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: cockpit enable
    ansible.posix.firewalld:
      zone: public 
      service: cockpit 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  