---
- name: collectd
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: collectd enable
    ansible.posix.firewalld:
      zone: public 
      service: collectd 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  