---
- name: condor-collector
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: condor-collector enable
    ansible.posix.firewalld:
      zone: public 
      service: condor-collector 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  