---
- name: dhcpv6-client
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: dhcpv6-client enable
    ansible.posix.firewalld:
      zone: public 
      service: dhcpv6-client 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  