---
- name: dns-over-tls
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: dns-over-tls enable
    ansible.posix.firewalld:
      zone: public 
      service: dns-over-tls 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  