---
- name: dns
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: dns enable
    ansible.posix.firewalld:
      zone: public 
      service: dns 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  