---
- name: docker-registry
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: docker-registry enable
    ansible.posix.firewalld:
      zone: public 
      service: docker-registry 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  