---
- name: elasticsearch
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: elasticsearch enable
    ansible.posix.firewalld:
      zone: public 
      service: elasticsearch 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  