---
- name: foreman
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: foreman enable
    ansible.posix.firewalld:
      zone: public 
      service: foreman 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  