---
- name: freeipa-trust
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: freeipa-trust enable
    ansible.posix.firewalld:
      zone: public 
      service: freeipa-trust 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  