---
- name: galera
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: galera enable
    ansible.posix.firewalld:
      zone: public 
      service: galera 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  