---
- name: ganglia-master
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ganglia-master enable
    ansible.posix.firewalld:
      zone: public 
      service: ganglia-master 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  