---
- name: git
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: git enable
    ansible.posix.firewalld:
      zone: public 
      service: git 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  