---
- name: grafana
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: grafana enable
    ansible.posix.firewalld:
      zone: public 
      service: grafana 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  