---
- name: https
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: https enable
    ansible.posix.firewalld:
      zone: public 
      service: https 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  