---
- name: ident
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ident enable
    ansible.posix.firewalld:
      zone: public 
      service: ident 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  