---
- name: ipfs
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ipfs enable
    ansible.posix.firewalld:
      zone: public 
      service: ipfs 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  