---
- name: ipp-client
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ipp-client enable
    ansible.posix.firewalld:
      zone: public 
      service: ipp-client 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  