---
- name: ipsec
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ipsec enable
    ansible.posix.firewalld:
      zone: public 
      service: ipsec 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  