---
- name: irc
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: irc enable
    ansible.posix.firewalld:
      zone: public 
      service: irc 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  