---
- name: iscsi-target
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: iscsi-target enable
    ansible.posix.firewalld:
      zone: public 
      service: iscsi-target 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  