---
- name: isns
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: isns enable
    ansible.posix.firewalld:
      zone: public 
      service: isns 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  