---
- name: jenkins
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: jenkins enable
    ansible.posix.firewalld:
      zone: public 
      service: jenkins 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  