---
- name: kdeconnect
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: kdeconnect enable
    ansible.posix.firewalld:
      zone: public 
      service: kdeconnect 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  