---
- name: kerberos
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: kerberos enable
    ansible.posix.firewalld:
      zone: public 
      service: kerberos 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  