---
- name: klogin
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: klogin enable
    ansible.posix.firewalld:
      zone: public 
      service: klogin 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  