---
- name: kprop
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: kprop enable
    ansible.posix.firewalld:
      zone: public 
      service: kprop 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  