---
- name: kube-controller-manager-secure
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: kube-controller-manager-secure enable
    ansible.posix.firewalld:
      zone: public 
      service: kube-controller-manager-secure 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  