---
- name: kube-apiserver
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: kube-apiserver enable
    ansible.posix.firewalld:
      zone: public 
      service: kube-apiserver 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  