---
- name: kubelet-worker
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: kubelet-worker enable
    ansible.posix.firewalld:
      zone: public 
      service: kubelet-worker 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  