---
- name: kube-scheduler-secure
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: kube-scheduler-secure enable
    ansible.posix.firewalld:
      zone: public 
      service: kube-scheduler-secure 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  