---
- name: kube-controller-manager
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: kube-controller-manager enable
    ansible.posix.firewalld:
      zone: public 
      service: kube-controller-manager 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  