---
- name: ldap
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ldap enable
    ansible.posix.firewalld:
      zone: public 
      service: ldap 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  