---
- name: lightning-network
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: lightning-network enable
    ansible.posix.firewalld:
      zone: public 
      service: lightning-network 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  