---
- name: llmnr
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: llmnr enable
    ansible.posix.firewalld:
      zone: public 
      service: llmnr 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  