---
- name: llmnr-tcp
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: llmnr-tcp enable
    ansible.posix.firewalld:
      zone: public 
      service: llmnr-tcp 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  