---
- name: mdns
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: mdns enable
    ansible.posix.firewalld:
      zone: public 
      service: mdns 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  