---
- name: memcache
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: memcache enable
    ansible.posix.firewalld:
      zone: public 
      service: memcache 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  