---
- name: mountd
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: mountd enable
    ansible.posix.firewalld:
      zone: public 
      service: mountd 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  