---
- name: mysql
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: mysql enable
    ansible.posix.firewalld:
      zone: public 
      service: mysql 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  