---
- name: netbios-ns
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: netbios-ns enable
    ansible.posix.firewalld:
      zone: public 
      service: netbios-ns 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  