---
- name: nfs3
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: nfs3 enable
    ansible.posix.firewalld:
      zone: public 
      service: nfs3 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  