---
- name: nmea-0183
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: nmea-0183 enable
    ansible.posix.firewalld:
      zone: public 
      service: nmea-0183 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  