---
- name: ntp
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ntp enable
    ansible.posix.firewalld:
      zone: public 
      service: ntp 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  