---
- name: ovirt-imageio
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ovirt-imageio enable
    ansible.posix.firewalld:
      zone: public 
      service: ovirt-imageio 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  