---
- name: ovirt-vmconsole
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ovirt-vmconsole enable
    ansible.posix.firewalld:
      zone: public 
      service: ovirt-vmconsole 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  