---
- name: plex
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: plex enable
    ansible.posix.firewalld:
      zone: public 
      service: plex 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  