---
- name: pmcd
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: pmcd enable
    ansible.posix.firewalld:
      zone: public 
      service: pmcd 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  