---
- name: pmproxy
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: pmproxy enable
    ansible.posix.firewalld:
      zone: public 
      service: pmproxy 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  