---
- name: pmwebapis
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: pmwebapis enable
    ansible.posix.firewalld:
      zone: public 
      service: pmwebapis 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  