---
- name: privoxy
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: privoxy enable
    ansible.posix.firewalld:
      zone: public 
      service: privoxy 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  