---
- name: prometheus-node-exporter
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: prometheus-node-exporter enable
    ansible.posix.firewalld:
      zone: public 
      service: prometheus-node-exporter 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  