---
- name: prometheus
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: prometheus enable
    ansible.posix.firewalld:
      zone: public 
      service: prometheus 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  