---
- name: proxy-dhcp
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: proxy-dhcp enable
    ansible.posix.firewalld:
      zone: public 
      service: proxy-dhcp 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  