---
- name: quassel
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: quassel enable
    ansible.posix.firewalld:
      zone: public 
      service: quassel 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  