---
- name: RH-Satellite-6-capsule
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: RH-Satellite-6-capsule enable
    ansible.posix.firewalld:
      zone: public 
      service: RH-Satellite-6-capsule 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  