---
- name: rpc-bind
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: rpc-bind enable
    ansible.posix.firewalld:
      zone: public 
      service: rpc-bind 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  