---
- name: rsh
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: rsh enable
    ansible.posix.firewalld:
      zone: public 
      service: rsh 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  