---
- name: rsyncd
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: rsyncd enable
    ansible.posix.firewalld:
      zone: public 
      service: rsyncd 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  