---
- name: samba-dc
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: samba-dc enable
    ansible.posix.firewalld:
      zone: public 
      service: samba-dc 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  