---
- name: sane
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: sane enable
    ansible.posix.firewalld:
      zone: public 
      service: sane 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  