---
- name: slp
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: slp enable
    ansible.posix.firewalld:
      zone: public 
      service: slp 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  