---
- name: smtp
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: smtp enable
    ansible.posix.firewalld:
      zone: public 
      service: smtp 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  