---
- name: smtps
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: smtps enable
    ansible.posix.firewalld:
      zone: public 
      service: smtps 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  