---
- name: snmptls
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: snmptls enable
    ansible.posix.firewalld:
      zone: public 
      service: snmptls 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  