---
- name: snmp
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: snmp enable
    ansible.posix.firewalld:
      zone: public 
      service: snmp 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  