---
- name: spideroak-lansync
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: spideroak-lansync enable
    ansible.posix.firewalld:
      zone: public 
      service: spideroak-lansync 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  