---
- name: spotify-sync
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: spotify-sync enable
    ansible.posix.firewalld:
      zone: public 
      service: spotify-sync 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  