---
- name: squid
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: squid enable
    ansible.posix.firewalld:
      zone: public 
      service: squid 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  