---
- name: ssh
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ssh enable
    ansible.posix.firewalld:
      zone: public 
      service: ssh 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  