---
- name: synergy
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: synergy enable
    ansible.posix.firewalld:
      zone: public 
      service: synergy 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  