---
- name: syslog-tls
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: syslog-tls enable
    ansible.posix.firewalld:
      zone: public 
      service: syslog-tls 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  