---
- name: telnet
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: telnet enable
    ansible.posix.firewalld:
      zone: public 
      service: telnet 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  