---
- name: tinc
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: tinc enable
    ansible.posix.firewalld:
      zone: public 
      service: tinc 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  