---
- name: tor-socks
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: tor-socks enable
    ansible.posix.firewalld:
      zone: public 
      service: tor-socks 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  