---
- name: transmission-client
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: transmission-client enable
    ansible.posix.firewalld:
      zone: public 
      service: transmission-client 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  