---
- name: vnc-server
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: vnc-server enable
    ansible.posix.firewalld:
      zone: public 
      service: vnc-server 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  