---
- name: wireguard
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: wireguard enable
    ansible.posix.firewalld:
      zone: public 
      service: wireguard 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  