---
- name: ws-discovery
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ws-discovery enable
    ansible.posix.firewalld:
      zone: public 
      service: ws-discovery 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  