---
- name: ws-discovery-tcp
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: ws-discovery-tcp enable
    ansible.posix.firewalld:
      zone: public 
      service: ws-discovery-tcp 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  