---
- name: wsman
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: wsman enable
    ansible.posix.firewalld:
      zone: public 
      service: wsman 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  