---
- name: wsmans
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: wsmans enable
    ansible.posix.firewalld:
      zone: public 
      service: wsmans 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  