---
- name: zabbix-agent
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: zabbix-agent enable
    ansible.posix.firewalld:
      zone: public 
      service: zabbix-agent 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  