---
- name: zerotier
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: zerotier enable
    ansible.posix.firewalld:
      zone: public 
      service: zerotier 
      permanent: yes
      state: enabled

  - name: firewall reload
    service:
      name: firewalld
      state: restarted  